server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flashrv
    username: flashrv
    password: flashrv
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/flashrv

flashrv:
  cors:
    allowedOrigins: "http://localhost:5173"
