version: "3.8"

services:
  kcdb:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - kcdb_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kcdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - kcdb
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes

  appdb:
    image: postgres:16
    environment:
      POSTGRES_DB: flashrv
      POSTGRES_USER: flashrv
      POSTGRES_PASSWORD: flashrv
    ports:
      - "5432:5432"
    volumes:
      - appdb_data:/var/lib/postgresql/data

volumes:
  kcdb_data:
  appdb_data:
